server:
  port: 8082
  servlet:
    context-path: /wechatone
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aaa.wechat.domain.model